package ni.shikatu.a50gramm.utlis

import org.drinkless.tdlib.TdApi
fun TdApi.Chat.copy(): TdApi.Chat {
	return TdApi.Chat(
		this.id,
		this.type,
		this.title,
		this.photo,
		this.accentColorId,
		this.backgroundCustomEmojiId,
		this.profileAccentColorId,
		this.profileBackgroundCustomEmojiId,
		this.permissions,
		this.lastMessage,
		this.positions,
		this.chatLists,
		this.messageSenderId,
		this.blockList,
		this.hasProtectedContent,
		this.isTranslatable,
		this.isMarkedAsUnread,
		this.viewAsTopics,
		this.hasScheduledMessages,
		this.canBeDeletedOnlyForSelf,
		this.canBeDeletedForAllUsers,
		this.canBeReported,
		this.defaultDisableNotification,
		this.unreadCount,
		this.lastReadInboxMessageId,
		this.lastReadOutboxMessageId,
		this.unreadMentionCount,
		this.unreadReactionCount,
		this.notificationSettings,
		this.availableReactions,
		this.messageAutoDeleteTime,
		this.emojiStatus,
		this.background,
		this.themeName,
		this.actionBar,
		this.businessBotManageBar,
		this.videoChat,
		this.pendingJoinRequests,
		this.replyMarkupMessageId,
		this.draftMessage,
		this.clientData
	)
}